/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: PingData.h
  Source: C:\Users\mcdl\Documents\_develop\DDS_Poco_Apps\5_source\DDS_Poco_Apps\_idl\PingData.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC_PINGDATA_H
#define DDSC_PINGDATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct PingData_PingMsg
{
  int32_t lPingID;
  char * sSourceHost;
  char * sPayload;
} PingData_PingMsg;

extern const dds_topic_descriptor_t PingData_PingMsg_desc;

#define PingData_PingMsg__alloc() \
((PingData_PingMsg*) dds_alloc (sizeof (PingData_PingMsg)));

#define PingData_PingMsg_free(d,o) \
dds_sample_free ((d), &PingData_PingMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PINGDATA_H */
