/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: PongData.h
  Source: C:\Users\mcdl\Documents\_develop\DDS_Poco_Apps\5_source\DDS_Poco_Apps\_idl\PongData.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC_PONGDATA_H
#define DDSC_PONGDATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct PongData_PongMsg
{
  int32_t lPongID;
  int32_t lOriPingID;
  char * sResponderHost;
  char * sPayload;
} PongData_PongMsg;

extern const dds_topic_descriptor_t PongData_PongMsg_desc;

#define PongData_PongMsg__alloc() \
((PongData_PongMsg*) dds_alloc (sizeof (PongData_PongMsg)));

#define PongData_PongMsg_free(d,o) \
dds_sample_free ((d), &PongData_PongMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PONGDATA_H */
